# Generated by Django 3.2.6 on 2021-08-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
