# Generated by Django 3.2.6 on 2021-08-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_treasure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
