# Generated by Django 3.2.6 on 2021-08-16 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasure', '0003_alter_treasure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='hunters',
            field=models.ManyToManyField(blank=True, related_name='hunter_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
