# Generated by Django 3.2.6 on 2021-08-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0004_alter_treasure_hunters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
