# Generated by Django 3.2.6 on 2021-08-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0005_auto_20210816_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treasure',
            name='hint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treasure',
            name='mcq1',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treasure',
            name='mcq2',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treasure',
            name='mcq3',
            field=models.CharField(default=3, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treasure',
            name='quiz',
            field=models.TextField(blank=True),
        ),
    ]
