# Generated by Django 3.2.6 on 2021-08-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0006_auto_20210817_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasure',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='treasure',
            old_name='longitude',
            new_name='lng',
        ),
    ]
