# Generated by Django 3.2.6 on 2021-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0007_auto_20210817_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='money',
            field=models.CharField(default='$', max_length=1000),
        ),
    ]
