# Generated by Django 3.2.6 on 2021-08-13 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direct_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rec_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
