# Generated by Django 3.2.6 on 2021-08-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_src',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
