# Generated by Django 3.2.6 on 2021-08-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20210819_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_src',
            field=models.CharField(default='https://c.files.bbci.co.uk/16620/production/_91408619_55df76d5-2245-41c1-8031-07a4da3f313f.jpg', max_length=1000),
        ),
    ]
