# Generated by Django 3.2.6 on 2021-08-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20210819_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
