# Generated by Django 3.2.6 on 2021-08-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_userprofile_age'),
        ('user_profile', '0009_alter_userprofile_age'),
    ]

    operations = [
    ]
