# Generated by Django 3.2.6 on 2021-08-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20210813_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='message',
            new_name='tweet',
        ),
    ]
