# Generated by Django 3.2.6 on 2021-08-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_rename_message_tweets_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='tweet',
            new_name='message',
        ),
    ]
