# Generated by Django 3.2.6 on 2021-08-17 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0007_alter_tweets_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='likes',
        ),
        migrations.AddField(
            model_name='tweets',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
