# Generated by Django 3.2.6 on 2021-08-18 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'NULL'), ('2', 'PENDING'), ('3', 'ACCEPT'), ('4', 'DECLINE')], default='NULL', max_length=300)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitee_id', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inteview_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
