# Generated by Django 3.2.6 on 2021-08-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_alter_invites_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='status',
            field=models.CharField(default='NULL', max_length=300),
        ),
    ]
