# Generated by Django 3.2.6 on 2021-08-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0004_alter_invites_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='status',
            field=models.CharField(choices=[('NULL', 'NULL'), ('PENDING', 'PENDING'), ('ACCEPT', 'ACCEPT'), ('DECLINE', 'DECLINE')], default='NULL', max_length=300),
        ),
    ]
